version: '3.4'

services:  
   core-nodejs-react:
    container_name: core-nodejs-react
    build:
      context: ./core-nodejs-react/
      dockerfile: Dockerfile
    networks:
       - overlay
    ports:
      - target: 3000      # port in contaner
        published: 82     # port in local
        protocol: tcp     #
        mode: ingress     #
    volumes:         
      - ./core-nodejs-react/:/usr/src/app/
    stdin_open: true
    tty: true  
  
  # Database management in a single PHP file
  # https://www.adminer.org/
  # adminer:
  #   image: adminer:latest
  #   container_name: adminer
  #   networks:
  #      - overlay
  #   restart: always
  #   ports:
  #     - 8080:8080
  
networks:
  overlay: