version: '3'
services:

  # The Application
  api:
    build:
      context: ./
      dockerfile: api.dockerfile
    working_dir: /var/www
    volumes:
      - ./api:/var/www/
    links:
      - "db:database"

  # The Web Server
  web:
    build:
      context: ./
      dockerfile: web.dockerfile
    working_dir: /var/www
    ports:
      - 8080:80

  # The Database
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    #user : root
    #password : example

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080

volumes:
  dbdata: