version: '3'

services:

    laravel: &laravel-template
      image: laravel:latest
      build:
        context: .
        args:
          - "BUILD_ARGUMENT_ENV=prod"
          - "BUILD_ARGUMENT_DEBUG_ENABLED=false"
        dockerfile: ./Dockerfile
      container_name: ${COMPOSE_PROJECT_NAME}_laravel
      restart: always
      expose:
        - 80
        - 443
      ports:
        - 80:80
        - 443:443
      depends_on:
        - mysql
      links:
        - mysql

    ### Cron tasks
    supervisord:
      <<: *laravel-template
      container_name: ${COMPOSE_PROJECT_NAME}_supervisord
      expose: []
      ports: []
      command: ["/usr/bin/supervisord"]

    mysql:
      image: mysql:8.0
      container_name: ${COMPOSE_PROJECT_NAME}_mysql
      restart: always
      command: --default-authentication-plugin=mysql_native_password
      environment:
        - MYSQL_ROOT_PASSWORD=secret
        - MYSQL_DATABASE=laravel
      volumes:
        - ./storage/mysql-data:/var/lib/mysql
